export type Role = "leader" | "co-leader" | "elder" | "member";

export interface Player {
  id: string;
  name: string;
  tag: string;
  role: Role;
  townHall: number;
  heroes: { king: number; queen: number; warden: number; champion: number };
  warStars: number;
  league: string;
}

export const PLAYERS: Player[] = [
  {
    id: "1",
    name: "BeastMode",
    tag: "#9QJV8Q9",
    role: "leader",
    townHall: 16,
    heroes: { king: 95, queen: 95, warden: 70, champion: 45 },
    warStars: 1450,
    league: "Legends",
  },
  {
    id: "2",
    name: "ValkyrieQueen",
    tag: "#8HJ22L",
    role: "co-leader",
    townHall: 16,
    heroes: { king: 90, queen: 95, warden: 68, champion: 40 },
    warStars: 1200,
    league: "Legends",
  },
  {
    id: "3",
    name: "IronFist",
    tag: "#PL099K",
    role: "co-leader",
    townHall: 15,
    heroes: { king: 85, queen: 90, warden: 60, champion: 35 },
    warStars: 980,
    league: "Titan I",
  },
  {
    id: "4",
    name: "GoblinKing",
    tag: "#MJJ882",
    role: "elder",
    townHall: 15,
    heroes: { king: 80, queen: 85, warden: 55, champion: 30 },
    warStars: 850,
    league: "Titan II",
  },
  {
    id: "5",
    name: "Wizardry",
    tag: "#UI288S",
    role: "elder",
    townHall: 14,
    heroes: { king: 75, queen: 80, warden: 50, champion: 25 },
    warStars: 720,
    league: "Titan III",
  },
  {
    id: "6",
    name: "ArcherGod",
    tag: "#HH123",
    role: "elder",
    townHall: 14,
    heroes: { king: 70, queen: 75, warden: 45, champion: 20 },
    warStars: 600,
    league: "Champion I",
  },
  {
    id: "7",
    name: "WallBreaker",
    tag: "#KKJ222",
    role: "member",
    townHall: 13,
    heroes: { king: 65, queen: 70, warden: 40, champion: 15 },
    warStars: 450,
    league: "Champion II",
  },
  {
    id: "8",
    name: "LavaHound",
    tag: "#LLL888",
    role: "member",
    townHall: 13,
    heroes: { king: 60, queen: 65, warden: 35, champion: 10 },
    warStars: 400,
    league: "Champion III",
  },
  {
    id: "9",
    name: "ElectroDrag",
    tag: "#EEE999",
    role: "member",
    townHall: 12,
    heroes: { king: 50, queen: 55, warden: 25, champion: 0 },
    warStars: 300,
    league: "Master I",
  },
  {
    id: "10",
    name: "BabyDrag",
    tag: "#BBB777",
    role: "member",
    townHall: 12,
    heroes: { king: 45, queen: 50, warden: 20, champion: 0 },
    warStars: 250,
    league: "Master II",
  },
  {
    id: "11",
    name: "EagleEye",
    tag: "#AAA111",
    role: "member",
    townHall: 11,
    heroes: { king: 40, queen: 40, warden: 10, champion: 0 },
    warStars: 180,
    league: "Master III",
  },
  {
    id: "12",
    name: "CannonCart",
    tag: "#CCC222",
    role: "member",
    townHall: 11,
    heroes: { king: 35, queen: 35, warden: 5, champion: 0 },
    warStars: 120,
    league: "Crystal I",
  },
  {
    id: "13",
    name: "NightWitch",
    tag: "#NNN333",
    role: "member",
    townHall: 11,
    heroes: { king: 30, queen: 30, warden: 5, champion: 0 },
    warStars: 100,
    league: "Crystal II",
  },
  {
    id: "14",
    name: "MegaKnight",
    tag: "#MMM444",
    role: "elder",
    townHall: 10,
    heroes: { king: 25, queen: 25, warden: 0, champion: 0 },
    warStars: 80,
    league: "Crystal III",
  },
  {
    id: "15",
    name: "IceGolem",
    tag: "#III555",
    role: "member",
    townHall: 10,
    heroes: { king: 20, queen: 20, warden: 0, champion: 0 },
    warStars: 60,
    league: "Gold I",
  },
  {
    id: "16",
    name: "HeadHunter",
    tag: "#HHH666",
    role: "co-leader",
    townHall: 17,
    heroes: { king: 95, queen: 95, warden: 70, champion: 45 },
    warStars: 2000,
    league: "Legends",
  },
  {
    id: "17",
    name: "SneakyGoblin",
    tag: "#SSS777",
    role: "member",
    townHall: 11,
    heroes: { king: 40, queen: 40, warden: 15, champion: 0 },
    warStars: 150,
    league: "Gold II",
  },
  {
    id: "18",
    name: "YetiSmash",
    tag: "#YYY888",
    role: "elder",
    townHall: 13,
    heroes: { king: 65, queen: 70, warden: 40, champion: 10 },
    warStars: 500,
    league: "Master I",
  },
  {
    id: "19",
    name: "SuperBarb",
    tag: "#BBB999",
    role: "member",
    townHall: 9,
    heroes: { king: 15, queen: 15, warden: 0, champion: 0 },
    warStars: 40,
    league: "Silver I",
  },
  {
    id: "20",
    name: "MinionHorde",
    tag: "#MMM000",
    role: "member",
    townHall: 9,
    heroes: { king: 10, queen: 10, warden: 0, champion: 0 },
    warStars: 20,
    league: "Silver II",
  },
];
